name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout LLVM
        uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          ref: refs/tags/llvmorg-19.1.7
          path: llvm-project

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          sdk: 10.0.19041.0

      - name: Configure CMake
        run: |
          cmake -S llvm-project/llvm -B build `
            -A x64 `
            -D CMAKE_SYSTEM_VERSION="10.0.19041.0" `
            -D BUILD_SHARED_LIBS=OFF `
            -D LLVM_ENABLE_ASSERTIONS=OFF `
            -D LLVM_ENABLE_PROJECTS="clang;clang-tools-extra" `
            -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded `
            -D CMAKE_ASM_MASM_FLAGS="/nologo" `
            -D CMAKE_BUILD_TYPE=MinSizeRel `
            -D CMAKE_C_FLAGS="/arch:znver3" `
            -D CMAKE_CXX_FLAGS="/arch:znver3" `
            -D LLVM_TARGETS_TO_BUILD="X86"

      - name: Build clang tools
        run: cmake --build build --config MinSizeRel --target clangd clang-format clang-tidy

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clang-tools
          path: |
            build/MinSizeRel/bin/clangd.exe
            build/MinSizeRel/bin/clang-format.exe
            build/MinSizeRel/bin/clang-tidy.exe
